### ISSUE TITLE
"Scoop update failed"

### ISSUE THREAD

**Issue by wendyyouthbaby** [neolee/pilot#448] opened 2019-11-08 13:50 UTC
1、已经尝试“ scoop uninstall git“和“ scoop install git”，但是进行“Scoop update ”的时候出现以下问题：
PS C:\Users\Administrator> scoop update
Updating Scoop...
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
ffatal: the remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed
Scoop update failed.

**Comment by neolee** [comment] 2019-11-08 13:58
你这一个问题已经发了三个 issue，为啥？

Duplicate of #446

**Closed by neolee** 2019-11-08 13:58 UTC
