### ISSUE TITLE
安装 Scoop 出错 `Exception calling "SetEnvironmentVariable" perform an unauthorized operation`

### ISSUE THREAD

**Issue by mydesire876** [neolee/pilot#52] opened 2019-10-24 06:57 UTC
ConEmu打开的界面显示：
管理员：cmd(Admin)
<1>管理员：cmd
Microsoft windows[版本6.1.7601
Administrator@PC-20181016JBWS c:\Users\Administrator
  
请问我要怎么调整一下？谢谢！

**Comment by mydesire876** [comment] 2019-10-24 07:07
![微信图片_20191024150337](https://user-images.githubusercontent.com/53138292/67461436-eaa51180-f66f-11e9-87ff-dccf3889cbfd.jpg)

**Comment by mydesire876** [comment] 2019-10-24 07:18
安装软件包管理工具 Scoop 重先安装还是有问题
![微信图片_20191024151652](https://user-images.githubusercontent.com/53138292/67462105-79fef480-f671-11e9-9dfe-0b289e0bf8c6.jpg)

**Comment by mydesire876** [comment] 2019-10-24 07:36
还是不行
![微信图片_20191024153250](https://user-images.githubusercontent.com/53138292/67463414-f7c3ff80-f673-11e9-94ba-3d355e535afc.jpg)
![微信图片_20191024153253](https://user-images.githubusercontent.com/53138292/67463437-00b4d100-f674-11e9-9054-2a6b97b63fb7.jpg)

**Comment by mydesire876** [comment] 2019-10-24 08:48
老师 还是不行
![微信图片_20191024164537](https://user-images.githubusercontent.com/53138292/67468983-0ca59080-f67e-11e9-98e9-c54a7b708c71.jpg)
![微信图片_20191024164543](https://user-images.githubusercontent.com/53138292/67468998-14fdcb80-f67e-11e9-988f-f41d74250807.jpg)

**Comment by neolee** [comment] 2019-10-25 15:49
Duplicate of #17

**Closed by neolee** 2019-10-25 15:49 UTC
