### ISSUE TITLE
运行 scoop update 命令，提示让先安装 git，运行 scoop install git 命令，提示“无法连接到远程服务器”

### ISSUE THREAD

**Issue by LazzaroneS** [neolee/pilot#8] opened 2019-10-22 16:51 UTC
过程如下：
PS C:\Users\L> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\L> scoop install git
Installing 'git' (2.23.0.windows.1) [64bit]
无法连接到远程服务器
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid

**Comment by neolee** [comment] 2019-10-23 02:56
Duplicate of #7

**Comment by LazzaroneS** [comment] 2019-10-23 09:48
明白了

**Closed** 2019-10-23 09:50 UTC
