### ISSUE TITLE
课程练习input2，input3

### ISSUE THREAD

**Issue by peakerzhu** [neolee/pilot#227] opened 2019-10-30 03:10 UTC
(base) peakzhueMacBook:Code peakzhu$ python good.py
How are you today?
good
Traceback (most recent call last):
  File "good.py", line 2, in <module>
    feeling = input()
  File "<string>", line 1, in <module>
NameError: name 'good' is not defined
(base) peakzhueMacBook:Code peakzhu$ python good.py
How are you today?
sad
Traceback (most recent call last):
  File "good.py", line 2, in <module>
    feeling = input()
  File "<string>", line 1, in <module>
NameError: name 'sad' is not defined

**Comment by neolee** [comment] 2019-10-30 05:17
Duplicate of #226

**Closed by neolee** 2019-10-30 05:17 UTC
