### ISSUE TITLE
已安装scoop.但运行scoop要跟新？怎么解？

### ISSUE THREAD

**Issue by guansheji** [neolee/pilot#218] opened 2019-10-29 15:59 UTC
![批注 2019-10-29 235136](https://user-images.githubusercontent.com/55250000/67785385-0f521c80-faa8-11e9-9f48-683483bdc61f.png)

**Comment by neolee** [comment] 2019-10-29 16:00
不要重复发 issue

Duplicate of #217

**Closed by neolee** 2019-10-29 16:00 UTC
